# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LikeSeries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('actors', models.CharField(blank=True, max_length=200)),
                ('overview', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, choices=[(b'Horror', b'Horror'), (b'Drama', b'Drama'), (b'Comedy', b'Comedy'), (b'SciFi', b'SciFi'), (b'Action', b'Action'), (b'Period', b'Period')], max_length=10)),
                ('vote_avg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_id_liked', models.TextField(default=b'[]')),
                ('like_action', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
