# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LikeSeries', '0003_remove_user_likes_like_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_id_liked', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_likes',
            name='user',
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='User_Likes',
        ),
    ]
